name: Build Executables for Windows and macOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: false
        default: '1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-14]  # macos-14 supports Apple Silicon (ARM64)

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to your Python version

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv sync  # Assuming pyproject.toml is used; if requirements.txt, change to uv pip install -r requirements.txt

      - name: Install PyInstaller and Pillow (for icon conversion)
        run: uv pip install pyinstaller pillow  # If not in pyproject.toml, install additionally

      - name: Convert icon for Windows
        if: matrix.os == 'windows-latest'
        run: |
          uv run python -c "
          from PIL import Image
          icon = Image.open('icon/icon.png')
          icon.save('icon/icon.ico', format='ICO', sizes=[(256,256), (128,128), (64,64), (48,48), (32,32), (16,16)])
          "

      - name: Convert icon for macOS
        if: matrix.os == 'macos-14'
        run: |
          mkdir icon/icon.iconset
          sips -z 16 16     icon/icon.png --out icon/icon.iconset/icon_16x16.png
          sips -z 32 32     icon/icon.png --out icon/icon.iconset/icon_16x16@2x.png
          sips -z 32 32     icon/icon.png --out icon/icon.iconset/icon_32x32.png
          sips -z 64 64     icon/icon.png --out icon/icon.iconset/icon_32x32@2x.png
          sips -z 128 128   icon/icon.png --out icon/icon.iconset/icon_128x128.png
          sips -z 256 256   icon/icon.png --out icon/icon.iconset/icon_128x128@2x.png
          sips -z 256 256   icon/icon.png --out icon/icon.iconset/icon_256x256.png
          sips -z 512 512   icon/icon.png --out icon/icon.iconset/icon_256x256@2x.png
          sips -z 512 512   icon/icon.png --out icon/icon.iconset/icon_512x512.png
          sips -z 1024 1024 icon/icon.png --out icon/icon.iconset/icon_512x512@2x.png
          iconutil -c icns icon/icon.iconset -o icon/icon.icns
          rm -rf icon/icon.iconset

      - name: Build executable for Windows
        if: matrix.os == 'windows-latest'
        run: |
          uv run pyinstaller --onefile --icon=icon/icon.ico --name MyApp-v${{ inputs.version }} main.py
        shell: pwsh

      - name: Build executable for macOS
        if: matrix.os == 'macos-14'
        run: |
          uv run pyinstaller --onefile --icon=icon/icon.icns --name MyApp-v${{ inputs.version }} --windowed main.py
          # If needed for .app bundle, additionally handle Info.plist
          if [ -d "dist/MyApp-v${{ inputs.version }}.app" ]; then
            cp icon/icon.icns "dist/MyApp-v${{ inputs.version }}.app/Contents/Resources/"
            plutil -replace CFBundleIconFile -string icon.icns "dist/MyApp-v${{ inputs.version }}.app/Contents/Info.plist"
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}-v${{ inputs.version }}
          path: dist/
